# 1. 유망 섹터 리서치 태스크
sector_research_task:
  description: >
    현재 시장 상황과 {topic} 트렌드를 분석하여, 향후 6개월 내 가장 유망해 보이는
    투자 섹터 3개를 선정하고 그 이유를 보고하라.
  expected_output: >
    선정된 3개 섹터의 이름과 선정 이유를 명확하게 기술한 보고서.
  agent: sector_researcher

# 2. 티커 스크리닝 태스크
ticker_screening_task:
  description: >
    주어진 {market} 시장에서 거래 가능한 모든 종목의 티커를 수집하여 리스트로 반환하라.
  expected_output: >
    Python 리스트 형태의 티커 목록.
  agent: ticker_screener
  
# 3. 재무 데이터 수집 태스크
fundamental_fetching_task:
  description: >
    Ticker Screener에게서 전달받은 티커 목록을 바탕으로, 각 종목의 핵심 재무 지표(PER, PBR, EPS, DIV)를
    수집하여 데이터프레임 형태로 정리하라.
  expected_output: >
    종목 티커를 인덱스로 하고, 재무 지표들을 컬럼으로 하는 Pandas DataFrame.
  agent: fundamental_fetcher
  context:
    - ticker_screening_task # 이전 태스크의 결과물을 입력으로 사용

# 4. 가치 평가 태스크
valuation_task:
  description: >
    ...
  

# 최종 트레이딩 계획 수립 태스크
trade_planning_task:
  description: >
    Allocator에게서 전달받은 최적 포트폴리오 비중을 바탕으로,
    각 종목별 정확한 매수 수량과 주문 가격 전략을 포함한 최종 트레이딩 계획을 수립하라.
  expected_output: >
    매수할 종목, 수량, 목표 가격, 주문 방식(시장가/지정가) 등을 포함한
    구체적인 실행 계획 보고서
  agent: trader_planner
  context:
    - valuation_task
    - risk_analysis_task
    - allocation_task