trend_analysis_task:
  description: >
    KREconomicIndicatorTool, USEconomicIndicatorTool과 웹 검색을 활용하여, 현재 시점의 대한민국 거시 경제 상황과
    글로벌 기술/산업 트렌드를 종합적으로 분석하라.
    이를 바탕으로 향후 3~6개월간 가장 유망할 것으로 판단되는 투자 섹터(테마)를 1개 선정하고,
    그 선정 이유를 명확하게 설명하라.
  expected_output: >
    선정된 유망 투자 섹터 이름과 그 이유를 담은 분석 보고서.
    이 결과는 다음 Sector Researcher에게 전달될 것이다.
  agent: market_trend_analyst

sector_research_task:
  description: >
    'trend_analysis_task'로부터 전달받은 유망 투자 섹터에 대해 심층적인 분석을 수행하라.
    이전 태스크의 결과물(유망 투자 섹터 이름)을 명확히 인지하고,
    그 주제를 키워드로 사용하여 네이버 뉴스에서 관련 기업들을 찾아내야 한다.
  expected_output: >
    선정된 섹터와 관련된 주요 기업 리스트와 간단한 분석 요약.
  agent: sector_researcher
  context:
    - trend_analysis_task

ticker_screening_task:
  description: >
    'sector_research_task'에서 전달받은 유망 섹터 정보를 바탕으로,
    {market} 시장에서 해당 섹터에 속하는 모든 종목의 티커를 수집하여 리스트로 반환하라.
  expected_output: >
    Python 리스트 형태의 티커 목록.
  agent: ticker_screener
  context:
    - sector_research_task

fundamental_fetching_task:
  description: >
    'ticker_screening_task'에서 전달받은 티커 목록 중, 시가총액 상위 5개 종목에 대해서만
    핵심 재무 지표(PER, PBR, EPS, DIV)를 수집하여 데이터프레임 형태로 정리하라.
  expected_output: >
    상위 5개 종목의 재무 지표를 담은 Pandas DataFrame.
  agent: fundamental_fetcher
  context:
    - ticker_screening_task

valuation_analysis_task:
  description: >
    'fundamental_fetching_task'에서 전달받은 5개 종목의 재무 데이터를 기반으로,
    ValuationTool을 사용하여 멀티 팩터 점수를 매기고 투자 매력도를 평가하라.
  expected_output: >
    각 종목의 투자 매력도 점수와 간단한 평가 요약을 담은 보고서.
  agent: valuation_analyst
  context:
    - fundamental_fetching_task

esg_analysis_task:
  description: >
    'valuation_analysis_task'에서 긍정적으로 평가된 종목들에 대해,
    웹 검색을 활용하여 각 기업의 ESG(환경, 사회, 지배구조) 관련 부정적 뉴스가 있는지 심층적으로 조사하라.
    (예: 환경 규제 위반, 부당 노동 행위, 경영진의 비윤리적 문제 등)
  expected_output: >
    각 종목별 ESG 리스크 분석 보고서. 심각한 문제가 발견된 경우 '투자 부적합'으로 명시할 것.
  agent: esg_analyst
  context:
    - valuation_analysis_task

insider_ownership_analysis_task:
  description: >
    'valuation_analysis_task'에서 평가된 종목들에 대해,
    InsiderAnalysisTool을 사용하여 기관의 자금 흐름을 분석하라.
  expected_output: >
    기관의 순매수/순매도 동향과 자금 흐름 분석 결과를 담은 보고서.
  agent: insider_ownership_analyst
  context:
    - esg_analysis_task

risk_analysis_task:
  description: >
    'insider_ownership_analysis_task'의 분석 결과를 참고하여 최종 후보 종목들을 선정하고,
    RiskAnalysisTool을 사용하여 종목들 간의 상관관계 매트릭스를 생성하고 리스크를 분석하라.
  expected_output: >
    종목 간 상관관계 분석 및 포트폴리오 분산 효과에 대한 리스크 분석 보고서.
  agent: risk_analyst
  context:
    - insider_ownership_analysis_task

allocation_task:
  description: >
    지금까지의 모든 분석 결과(가치 평가, 기관 동향, 리스크 분석)를 종합하여,
    AllocationTool을 사용하여 최종 포트폴리오의 각 종목별 투자 비중을 결정하라.
  expected_output: >
    각 종목의 이름과 할당된 투자 비중(%)을 명시한 최종 포트폴리오 구성안.
  agent: allocator
  context:
    - valuation_analysis_task
    - esg_analysis_task
    - insider_ownership_analysis_task
    - risk_analysis_task

trade_planning_task:
  description: >
    'allocation_task'에서 결정된 포트폴리오 구성안을 바탕으로 최종 매매 계획을 수립하라.
    현재 투자에 사용할 수 있는 총 가용 현금은 가장 첫 단계에서 분석한 포트폴리오 상태의 'cash' 값이다.
    이 가용 현금을 사용하여 TradePlannerTool로 구체적인 매수 주문 계획을 수립해야 한다.
  expected_output: >
    매수할 종목, 주문 방식, 매수 수량, 예상 주문 금액 등을 포함한 최종 실행 계획 보고서.
    이 보고서를 'trading_plan.md' 파일로 저장하라.
  agent: trader_planner
  context:
    - allocation_task
  output_file: 'trading_plan.md'

trade_execution_task:
  description: >
    'trade_planning_task'에서 수립된 최종 매매 계획을 검토하고,
    계획에 명시된 각 종목에 대해 TradeExecutorTool을 사용하여
    매수 주문을 정확하게 실행하라.
  expected_output: >
    모든 주문의 실행 결과 요약 보고서
  agent: trade_executor
  context:
    - trade_planning_task